RAPIDOS-Y_FURIOSOS:
  drivername: postgresql
  user: postgres
  password: postgres
  port: 5432
  host: 192.168.1.135
  dbname: rapidos_y_furiosos

ETL_RYF:
  drivername: postgresql
  user: postgres
  password: postgres
  port: 5432
  host: 192.168.1.135
  dbname: ETL-rapidos-y-furiosos

LOAD_DIMENSIONS: True