RAPIDOS-Y_FURIOSOS:
  drivername: postgresql
  user: oswaldo
  password: Lukas12345
  port: 5432
  host: localhost
  dbname: rapidos_y_furiosos

ETL_RYF:
  drivername: postgresql
  user: oswaldo
  password: Lukas12345
  port: 5432
  host: localhost
  dbname: ETL-rapidos-y-furiosos

LOAD_DIMENSIONS: True